/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: 'var(--color-primary)',
        'primary-deep': 'var(--color-primary-deep)',
        'sunshine-300': 'var(--color-sunshine-300)',
        'sunshine-500': 'var(--color-sunshine-500)',
        'sunshine-700': 'var(--color-sunshine-700)',
        'sunshine-800': 'var(--color-sunshine-800)',
        'sunshine-900': 'var(--color-sunshine-900)',
        'yellow-saturated': 'var(--color-yellow-saturated)',
        cream: 'var(--color-cream)',
        'cream-soft': 'var(--color-cream-soft)',
        'cream-deeper': 'var(--color-cream-deeper)',
        'beige-deep': 'var(--color-beige-deep)',
        canvas: 'var(--color-canvas)',
        surface: 'var(--color-surface)',
        'surface-cream': 'var(--color-surface-cream)',
        'surface-code': 'var(--color-surface-code)',
        hairline: 'var(--color-hairline)',
        'hairline-soft': 'var(--color-hairline-soft)',
        'hairline-strong': 'var(--color-hairline-strong)',
        ink: 'var(--color-ink)',
        'ink-tint': 'var(--color-ink-tint)',
        charcoal: 'var(--color-charcoal)',
        slate: 'var(--color-slate)',
        steel: 'var(--color-steel)',
        stone: 'var(--color-stone)',
        muted: 'var(--color-muted)',
        'on-dark': 'var(--color-on-dark)',
        'on-dark-muted': 'var(--color-on-dark-muted)',
        link: 'var(--color-link)',
        error: 'var(--color-error)',
        warning: 'var(--color-warning)',
        success: 'var(--color-success)',
      },
      fontFamily: {
        display: ['Playfair Display', "'Times New Roman'", 'Georgia', 'serif'],
        sans: ['Inter', 'ui-sans-serif', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', "'SF Mono'", 'Menlo', 'Consolas', 'monospace'],
      },
      borderRadius: {
        xs: '4px',
        sm: '6px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        xxl: '20px',
        full: '9999px',
      },
      letterSpacing: {
        'display': '-0.04em',
        'heading': '-0.02em',
      },
      boxShadow: {
        'subtle': '0px 1px 2px 0px rgba(0, 0, 0, 0.04)',
        'card': '0px 4px 12px 0px rgba(0, 0, 0, 0.04)',
        'mockup': '0px 12px 24px -4px rgba(0, 0, 0, 0.08)',
        'modal': '0px 16px 48px -8px rgba(0, 0, 0, 0.12)',
      },
    },
  },
  plugins: [],
}
